### ISSUE TITLE
fluentd_logger ruby process using 80% memory and causing instance to restart

### ISSUE THREAD

**Issue by bonesyo** [GoogleCloudPlatform/appengine-sidecars-docker#87] opened 2017-12-19 22:22 UTC
## Urgent

fluentd has been utilizing the majority of the instances allocated memory and starving our app of memory, until the fluentd process gets killed, or the instance restarts. I believe that this has been going on for about 2 months, before then we were not noticing this issue. There seems to be others experiencing the same issue.

This has been creating a noticeable slowdown for our customers and this is something we need to resolve ASAP. If anyone has any ideas on what could be causing this, that would be great.

`Dec 17 21:17:59 aef-api--terminal-1--19--0-ck2r kernel: [141421.123211] Out of memory: Kill process 3407 (ruby) score 234 or sacrifice child`
`Dec 17 21:17:59 aef-api--terminal-1--19--0-ck2r kernel: [141421.130926] Killed process 3407 (ruby) total-vm:883508kB, anon-rss:239232kB, file-rss:0kB 
  undefined
`

https://stackoverflow.com/questions/47844344/how-to-limit-the-fluentd-logger-memory-usage-in-a-google-app-engine-java-flexibl?noredirect=1&lq=1

https://stackoverflow.com/questions/47759924/google-cloud-platform-app-engine-node-flexible-instance-ruby-sitting-at-50-ram

**Comment by Cynocracy** [comment] 2018-01-02 22:05
Apologies for the late response.

This is a known issue caused by a memory leak in the google-cloud-logging plugin fixed by:
https://github.com/GoogleCloudPlatform/appengine-sidecars-docker/pull/86

We were made aware of the issue through standard support channels on Dec 14th, and have taken steps to move all customers off of images with the broken sidecar as of Dec 20th. If you believe this is still occurring with your application, feel free to reopen and we will investigate.

**Closed by Cynocracy** 2018-01-02 22:05 UTC

**Comment by bonesyo** [comment] 2018-01-02 22:28
@Cynocracy Thank you for the response! What can I do to ensure we are on the new image? It does not seem to be running away anymore, but our fluentd process seems to be running around 23% (230mb). Does this sound normal to you?

**Comment by Cynocracy** [comment] 2018-01-02 23:26
Fluentd has been seen to be fairly resource intensive in the past (especially depending on the log volume). 230mb doesn't sound unreasonable to me, so long as the usage isn't growing continuously as you saw before.

You can check that you're on the newest image (or at least an unaffected image) by checking the version of the google-cloud-logging plugin in the fluentd sidecar:

`
sudo su
docker exec -it fluentd_logger google-fluentd-gem list fluent-plugin-google-cloud
`

This will show 0.6.8 if the image is impacted by the memory leak, and another version (likely 0.6 or 0.6.12) if not.

**Comment by bonesyo** [comment] 2018-01-02 23:42
@Cynocracy I just ran that command and we are on 0.6.8. How do I update to 0.6.12?

**Comment by Cynocracy** [comment] 2018-01-03 00:43
Redeploying should pick up the latest image (with a fixed sidecar).

If you file a support request and reference this, I'd be happy to dig into why you ended up with the memleaked sidecar.

**Comment by Cynocracy** [comment] 2018-01-03 01:30
Ah, I apologize, I was slightly inaccurate, it looks like the issue was in reality introduced by grpc >= 1.3

Checking the version of the grpc plugin reveals

grpc (1.2.5 x86_64-linux) on the "latest" image (actually a rollback), despite the command I pasted above showing fluent-plugin-google-cloud (0.6.8, 0.6.0).

I'm admittedly not an expert on the gem system, but it appears the memory leak isn't included so long as the grpc output is < 1.3. Which means we're good :)

**Comment by bonesyo** [comment] 2018-01-03 22:05
Ok, it looks like we are on 1.2.5! Thank you for the help!
